### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку virt_mem_max Горбунов Егор 

### ISSUE THREAD

**Issue by egorbunov** [egorbunov/au-linux-kernel-spring-2016#3]
https://github.com/egorbunov/au-linux-kernel-spring-2016/commit/910e66b3a600fccfd44dac547c5af6bb8c3153c6

Я вот исправил немного: https://github.com/egorbunov/au-linux-kernel-spring-2016/commit/5771e34b8273a8e546f55154c1fffb5db7c17f7c

**Comment by eabatalov** [comment]
Ok. fs is ignored for anonymous mmap.
100 points out of 100.
